[package]
name = "lean-tidy"
version = "0.1"
lean_version = "3.4.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "8c385bc404640d7f131ffaf2611eeeb7943dc7f6"}
libk = {git = "https://github.com/khoek/libk", rev = "461caf0b2915dd612a5e9f4ad7f6b627506d4ec0"}
lean-rewrite-search = {git = "https://github.com/khoek/lean-rewrite-search", rev = "e2b7115b82f428f43c05e012c43fafcf3ac42eba"}
